/**
 * Demo data — used while Supabase is not configured. Lets the app render
 * fully so the founder can pitch, walk the souqs, and onboard craftsmen
 * before the backend is hot. Replaced by real data once env vars are set.
 */

import type {
  City,
  Trade,
  AssetType,
  Craftsman,
  Service,
  WorkshopAsset,
  MapZone,
  SubscriptionPlan,
  Channel,
} from "./types";

export const DEMO_CITIES: City[] = [
  { id: 1, name_ar: "دمشق", name_en: "Damascus", country: "SY" },
  {
    id: 2,
    name_ar: "ريف دمشق",
    name_en: "Rif Dimashq",
    country: "SY",
  },
];

export const DEMO_TRADES: Trade[] = [
  {
    id: 1,
    name_ar: "نجار",
    name_en: "Carpenter",
    icon: "hammer",
    is_approved: true,
    submitted_by: null,
    approved_by: null,
    created_at: "",
  },
  {
    id: 2,
    name_ar: "حداد",
    name_en: "Blacksmith",
    icon: "anvil",
    is_approved: true,
    submitted_by: null,
    approved_by: null,
    created_at: "",
  },
  {
    id: 3,
    name_ar: "كهربائي",
    name_en: "Electrician",
    icon: "zap",
    is_approved: true,
    submitted_by: null,
    approved_by: null,
    created_at: "",
  },
  {
    id: 4,
    name_ar: "سباك",
    name_en: "Plumber",
    icon: "wrench",
    is_approved: true,
    submitted_by: null,
    approved_by: null,
    created_at: "",
  },
  {
    id: 5,
    name_ar: "دهان",
    name_en: "Painter",
    icon: "paintbrush",
    is_approved: true,
    submitted_by: null,
    approved_by: null,
    created_at: "",
  },
  {
    id: 6,
    name_ar: "بلّاط",
    name_en: "Tiler",
    icon: "grid",
    is_approved: true,
    submitted_by: null,
    approved_by: null,
    created_at: "",
  },
  {
    id: 7,
    name_ar: "لحّام",
    name_en: "Welder",
    icon: "flame",
    is_approved: true,
    submitted_by: null,
    approved_by: null,
    created_at: "",
  },
  {
    id: 8,
    name_ar: "ألمنيوم",
    name_en: "Aluminum Worker",
    icon: "layers",
    is_approved: true,
    submitted_by: null,
    approved_by: null,
    created_at: "",
  },
  {
    id: 9,
    name_ar: "حجّار",
    name_en: "Stonemason",
    icon: "mountain",
    is_approved: true,
    submitted_by: null,
    approved_by: null,
    created_at: "",
  },
  {
    id: 10,
    name_ar: "ميكانيكي",
    name_en: "Mechanic",
    icon: "settings",
    is_approved: true,
    submitted_by: null,
    approved_by: null,
    created_at: "",
  },
  {
    id: 11,
    name_ar: "خراط",
    name_en: "Turner",
    icon: "disc",
    is_approved: true,
    submitted_by: null,
    approved_by: null,
    created_at: "",
  },
  {
    id: 12,
    name_ar: "زجاج",
    name_en: "Glassworker",
    icon: "square",
    is_approved: true,
    submitted_by: null,
    approved_by: null,
    created_at: "",
  },
];

export const DEMO_ASSET_TYPES: AssetType[] = [
  { id: 1, name_ar: "منشار كهربائي", name_en: "Electric Saw", trade_id: 1 },
  { id: 2, name_ar: "مخرطة خشب", name_en: "Wood Lathe", trade_id: 1 },
  {
    id: 3,
    name_ar: "آلة لحام بلازما",
    name_en: "Plasma Welder",
    trade_id: 7,
  },
  { id: 4, name_ar: "آلة لحام أرغون", name_en: "Argon Welder", trade_id: 7 },
  {
    id: 5,
    name_ar: "مولدة كهرباء",
    name_en: "Power Generator",
    trade_id: null,
  },
  {
    id: 6,
    name_ar: "كومبريسر هواء",
    name_en: "Air Compressor",
    trade_id: null,
  },
  { id: 7, name_ar: "مكبس هيدروليك", name_en: "Hydraulic Press", trade_id: 2 },
  { id: 8, name_ar: "ثاقبة عمودية", name_en: "Drill Press", trade_id: 2 },
  { id: 9, name_ar: "آلة بلاط", name_en: "Tile Cutter", trade_id: 6 },
  { id: 10, name_ar: "ضاغط هواء كبير", name_en: "Industrial Compressor", trade_id: 5 },
];

const damascusNeighborhoods: Array<{ name: string; coords: [number, number] }> = [
  { name: "حوش بلاس", coords: [33.5215, 36.3055] },
  { name: "الميدان", coords: [33.4905, 36.3045] },
  { name: "باب توما", coords: [33.5145, 36.3125] },
  { name: "القصاع", coords: [33.5195, 36.3095] },
  { name: "الشاغور", coords: [33.5023, 36.305] },
  { name: "ساحة العباسيين", coords: [33.5295, 36.328] },
  { name: "كفرسوسة", coords: [33.488, 36.272] },
  { name: "المزة", coords: [33.503, 36.246] },
  { name: "ركن الدين", coords: [33.534, 36.292] },
  { name: "جوبر", coords: [33.524, 36.347] },
  { name: "سقبا", coords: [33.519, 36.405] },
  { name: "دوما", coords: [33.572, 36.404] },
];

export const DEMO_CRAFTSMEN: Craftsman[] = [
  {
    id: "demo-1",
    user_id: null,
    city_id: 1,
    name: "أبو محمود الدمشقي",
    trade_id: 1,
    custom_trade_name: null,
    bio_ar: "نجار من زمان الباب التوماني، شغل خشب جوز وموبيليا قديمة.",
    bio_en: "Old Damascene carpenter — walnut wood, antique furniture work.",
    phone: "+963991234567",
    whatsapp: "+963991234567",
    instagram: null,
    facebook: null,
    photo_url: null,
    latitude: damascusNeighborhoods[2].coords[0],
    longitude: damascusNeighborhoods[2].coords[1],
    location_name: damascusNeighborhoods[2].name,
    status: "open",
    approval_status: "approved",
    approved_by: null,
    is_verified: true,
    is_elite: true,
    mode_pref: null,
    created_at: "",
    updated_at: "",
  },
  {
    id: "demo-2",
    user_id: null,
    city_id: 1,
    name: "معلم سامر الحداد",
    trade_id: 2,
    custom_trade_name: null,
    bio_ar: "حداد من حوش بلاس، عندي مكبس وآلة قص بلازما.",
    bio_en: "Blacksmith from Hosh Blass — hydraulic press + plasma cutter.",
    phone: "+963992345678",
    whatsapp: "+963992345678",
    instagram: "@samer.blacksmith",
    facebook: null,
    photo_url: null,
    latitude: damascusNeighborhoods[0].coords[0],
    longitude: damascusNeighborhoods[0].coords[1],
    location_name: damascusNeighborhoods[0].name,
    status: "busy",
    approval_status: "approved",
    approved_by: null,
    is_verified: true,
    is_elite: false,
    mode_pref: null,
    created_at: "",
    updated_at: "",
  },
  {
    id: "demo-3",
    user_id: null,
    city_id: 1,
    name: "أحمد الكهربائي",
    trade_id: 3,
    custom_trade_name: null,
    bio_ar: "كهربائي ورشات وأبنية، خبرة ١٥ سنة.",
    bio_en: "Workshop and building electrician, 15 years experience.",
    phone: "+963993456789",
    whatsapp: "+963993456789",
    instagram: null,
    facebook: "ahmed.electrician.dam",
    photo_url: null,
    latitude: damascusNeighborhoods[6].coords[0],
    longitude: damascusNeighborhoods[6].coords[1],
    location_name: damascusNeighborhoods[6].name,
    status: "open",
    approval_status: "approved",
    approved_by: null,
    is_verified: true,
    is_elite: false,
    mode_pref: null,
    created_at: "",
    updated_at: "",
  },
  {
    id: "demo-4",
    user_id: null,
    city_id: 1,
    name: "أبو خالد السبّاك",
    trade_id: 4,
    custom_trade_name: null,
    bio_ar: "سباك بيوت وفلل، شغل نظيف ومضمون.",
    bio_en: "Residential plumber, clean and reliable work.",
    phone: "+963994567890",
    whatsapp: "+963994567890",
    instagram: null,
    facebook: null,
    photo_url: null,
    latitude: damascusNeighborhoods[7].coords[0],
    longitude: damascusNeighborhoods[7].coords[1],
    location_name: damascusNeighborhoods[7].name,
    status: "open",
    approval_status: "approved",
    approved_by: null,
    is_verified: false,
    is_elite: false,
    mode_pref: null,
    created_at: "",
    updated_at: "",
  },
  {
    id: "demo-5",
    user_id: null,
    city_id: 1,
    name: "وليد الدهان",
    trade_id: 5,
    custom_trade_name: null,
    bio_ar: "دهان داخلي وخارجي، عندي رولات ومسدس رش.",
    bio_en: "Interior + exterior painter — rollers, spray gun.",
    phone: "+963995678901",
    whatsapp: "+963995678901",
    instagram: null,
    facebook: null,
    photo_url: null,
    latitude: damascusNeighborhoods[1].coords[0],
    longitude: damascusNeighborhoods[1].coords[1],
    location_name: damascusNeighborhoods[1].name,
    status: "open",
    approval_status: "approved",
    approved_by: null,
    is_verified: true,
    is_elite: false,
    mode_pref: null,
    created_at: "",
    updated_at: "",
  },
  {
    id: "demo-6",
    user_id: null,
    city_id: 1,
    name: "نزار البلّاط",
    trade_id: 6,
    custom_trade_name: null,
    bio_ar: "بلّاط رخام وسيراميك، شغل دقيق.",
    bio_en: "Marble and ceramic tiler, precision work.",
    phone: "+963996789012",
    whatsapp: "+963996789012",
    instagram: null,
    facebook: null,
    photo_url: null,
    latitude: damascusNeighborhoods[8].coords[0],
    longitude: damascusNeighborhoods[8].coords[1],
    location_name: damascusNeighborhoods[8].name,
    status: "open",
    approval_status: "approved",
    approved_by: null,
    is_verified: false,
    is_elite: false,
    mode_pref: null,
    created_at: "",
    updated_at: "",
  },
  {
    id: "demo-7",
    user_id: null,
    city_id: 1,
    name: "كريم اللحّام",
    trade_id: 7,
    custom_trade_name: null,
    bio_ar: "لحام أرغون وأكسجين، عندي مولدة وكومبريسر.",
    bio_en: "Argon and oxy-acetylene welding. Generator + compressor on site.",
    phone: "+963997890123",
    whatsapp: "+963997890123",
    instagram: null,
    facebook: null,
    photo_url: null,
    latitude: damascusNeighborhoods[9].coords[0],
    longitude: damascusNeighborhoods[9].coords[1],
    location_name: damascusNeighborhoods[9].name,
    status: "busy",
    approval_status: "approved",
    approved_by: null,
    is_verified: true,
    is_elite: true,
    mode_pref: null,
    created_at: "",
    updated_at: "",
  },
  {
    id: "demo-8",
    user_id: null,
    city_id: 2,
    name: "أبو عماد ساقبا",
    trade_id: 1,
    custom_trade_name: null,
    bio_ar: "نجار موبيليا من سقبا، خبرة ٢٥ سنة.",
    bio_en: "Furniture carpenter from Saqba, 25 years experience.",
    phone: "+963998901234",
    whatsapp: "+963998901234",
    instagram: null,
    facebook: null,
    photo_url: null,
    latitude: damascusNeighborhoods[10].coords[0],
    longitude: damascusNeighborhoods[10].coords[1],
    location_name: damascusNeighborhoods[10].name,
    status: "open",
    approval_status: "approved",
    approved_by: null,
    is_verified: true,
    is_elite: false,
    mode_pref: null,
    created_at: "",
    updated_at: "",
  },
  {
    id: "demo-9",
    user_id: null,
    city_id: 2,
    name: "محمود الدومي",
    trade_id: 8,
    custom_trade_name: null,
    bio_ar: "ألمنيوم وأبواب وشبابيك، شغل قياس.",
    bio_en: "Aluminum doors and windows, custom-fit.",
    phone: "+963999012345",
    whatsapp: "+963999012345",
    instagram: null,
    facebook: null,
    photo_url: null,
    latitude: damascusNeighborhoods[11].coords[0],
    longitude: damascusNeighborhoods[11].coords[1],
    location_name: damascusNeighborhoods[11].name,
    status: "open",
    approval_status: "approved",
    approved_by: null,
    is_verified: false,
    is_elite: false,
    mode_pref: null,
    created_at: "",
    updated_at: "",
  },
  {
    id: "demo-10",
    user_id: null,
    city_id: 1,
    name: "حسن الحجّار",
    trade_id: 9,
    custom_trade_name: null,
    bio_ar: "حجّار من المدينة القديمة، شغل حجر دمشقي.",
    bio_en: "Stonemason from the Old City — Damascene stonework.",
    phone: "+963990123456",
    whatsapp: "+963990123456",
    instagram: null,
    facebook: null,
    photo_url: null,
    latitude: damascusNeighborhoods[3].coords[0],
    longitude: damascusNeighborhoods[3].coords[1],
    location_name: damascusNeighborhoods[3].name,
    status: "open",
    approval_status: "approved",
    approved_by: null,
    is_verified: true,
    is_elite: true,
    mode_pref: null,
    created_at: "",
    updated_at: "",
  },
];

export const DEMO_SERVICES: Service[] = [
  {
    id: 1,
    craftsman_id: "demo-1",
    name_ar: "صناعة موبيليا حسب الطلب",
    name_en: "Custom furniture",
    description: null,
    starting_price: 500000,
    currency: "SYP",
  },
  {
    id: 2,
    craftsman_id: "demo-1",
    name_ar: "ترميم أبواب خشب قديمة",
    name_en: "Antique door restoration",
    description: null,
    starting_price: 300000,
    currency: "SYP",
  },
  {
    id: 3,
    craftsman_id: "demo-2",
    name_ar: "حداد بناء (شيش، أبواب، درابزين)",
    name_en: "Construction ironwork",
    description: null,
    starting_price: 200000,
    currency: "SYP",
  },
  {
    id: 4,
    craftsman_id: "demo-3",
    name_ar: "تمديدات كهربائية لشقة كاملة",
    name_en: "Full apartment wiring",
    description: null,
    starting_price: 800000,
    currency: "SYP",
  },
  {
    id: 5,
    craftsman_id: "demo-7",
    name_ar: "لحام هياكل معدنية",
    name_en: "Metal frame welding",
    description: null,
    starting_price: 250000,
    currency: "SYP",
  },
];

export const DEMO_WORKSHOP_ASSETS: WorkshopAsset[] = [
  {
    id: 1,
    craftsman_id: "demo-1",
    asset_type_id: 1,
    custom_name: null,
    is_verified: true,
  },
  {
    id: 2,
    craftsman_id: "demo-1",
    asset_type_id: 2,
    custom_name: null,
    is_verified: true,
  },
  {
    id: 3,
    craftsman_id: "demo-2",
    asset_type_id: 7,
    custom_name: null,
    is_verified: true,
  },
  {
    id: 4,
    craftsman_id: "demo-2",
    asset_type_id: 8,
    custom_name: null,
    is_verified: false,
  },
  {
    id: 5,
    craftsman_id: "demo-7",
    asset_type_id: 3,
    custom_name: null,
    is_verified: true,
  },
  {
    id: 6,
    craftsman_id: "demo-7",
    asset_type_id: 5,
    custom_name: null,
    is_verified: true,
  },
];

export const DEMO_ZONES: MapZone[] = [
  {
    id: 1,
    city_id: 1,
    name_ar: "سوق حوش بلاس",
    name_en: "Hosh Blass Market",
    type: "industrial",
    description: null,
    geojson: {
      type: "Polygon",
      coordinates: [
        [
          [36.298, 33.518],
          [36.314, 33.518],
          [36.314, 33.526],
          [36.298, 33.526],
          [36.298, 33.518],
        ],
      ],
    },
    color: "#1C2833",
    visibility: "public",
    is_active: true,
    created_by: null,
    created_at: "",
  },
  {
    id: 2,
    city_id: 1,
    name_ar: "المدينة القديمة",
    name_en: "Old City",
    type: "heritage",
    description: null,
    geojson: {
      type: "Polygon",
      coordinates: [
        [
          [36.305, 33.508],
          [36.318, 33.508],
          [36.318, 33.518],
          [36.305, 33.518],
          [36.305, 33.508],
        ],
      ],
    },
    color: "#8B4513",
    visibility: "public",
    is_active: true,
    created_by: null,
    created_at: "",
  },
  {
    id: 3,
    city_id: 2,
    name_ar: "إعمار سقبا",
    name_en: "Saqba Reconstruction",
    type: "construction",
    description: null,
    geojson: {
      type: "Polygon",
      coordinates: [
        [
          [36.394, 33.512],
          [36.418, 33.512],
          [36.418, 33.528],
          [36.394, 33.528],
          [36.394, 33.512],
        ],
      ],
    },
    color: "#C67B30",
    visibility: "firms_only",
    is_active: true,
    created_by: null,
    created_at: "",
  },
];

export const DEMO_PLANS: SubscriptionPlan[] = [
  {
    id: 1,
    name_ar: "أساسي",
    name_en: "Basic",
    target_audience: "firm",
    duration_type: "monthly",
    price: 0,
    currency: "USD",
    features: ["browse_profiles", "basic_search"],
    max_contacts_per_month: 5,
    max_ads: null,
    can_target_zones: false,
    can_target_categories: false,
    priority_placement: false,
    analytics_access: false,
    is_active: true,
  },
  {
    id: 2,
    name_ar: "احترافي",
    name_en: "Professional",
    target_audience: "firm",
    duration_type: "monthly",
    price: 30,
    currency: "USD",
    features: [
      "browse_profiles",
      "advanced_search",
      "save_teams",
      "capacity_filter",
      "reliability_scores",
    ],
    max_contacts_per_month: null,
    max_ads: null,
    can_target_zones: false,
    can_target_categories: true,
    priority_placement: false,
    analytics_access: true,
    is_active: true,
  },
  {
    id: 3,
    name_ar: "احترافي سنوي",
    name_en: "Professional Yearly",
    target_audience: "firm",
    duration_type: "yearly",
    price: 250,
    currency: "USD",
    features: [
      "browse_profiles",
      "advanced_search",
      "save_teams",
      "capacity_filter",
      "reliability_scores",
      "zone_targeting",
      "priority_support",
    ],
    max_contacts_per_month: null,
    max_ads: null,
    can_target_zones: true,
    can_target_categories: true,
    priority_placement: true,
    analytics_access: true,
    is_active: true,
  },
  {
    id: 4,
    name_ar: "إعلان واحد",
    name_en: "Single Ad",
    target_audience: "supplier",
    duration_type: "one_time",
    price: 10,
    currency: "USD",
    features: ["single_ad", "basic_targeting"],
    max_contacts_per_month: null,
    max_ads: 1,
    can_target_zones: false,
    can_target_categories: true,
    priority_placement: false,
    analytics_access: false,
    is_active: true,
  },
  {
    id: 5,
    name_ar: "باقة شهرية",
    name_en: "Monthly Package",
    target_audience: "supplier",
    duration_type: "monthly",
    price: 40,
    currency: "USD",
    features: [
      "unlimited_ads",
      "zone_targeting",
      "category_targeting",
      "basic_analytics",
    ],
    max_contacts_per_month: null,
    max_ads: 5,
    can_target_zones: true,
    can_target_categories: true,
    priority_placement: false,
    analytics_access: true,
    is_active: true,
  },
  {
    id: 6,
    name_ar: "باقة سنوية",
    name_en: "Yearly Package",
    target_audience: "supplier",
    duration_type: "yearly",
    price: 350,
    currency: "USD",
    features: [
      "unlimited_ads",
      "zone_targeting",
      "category_targeting",
      "full_analytics",
      "priority_placement",
      "featured_badge",
    ],
    max_contacts_per_month: null,
    max_ads: null,
    can_target_zones: true,
    can_target_categories: true,
    priority_placement: true,
    analytics_access: true,
    is_active: true,
  },
];

export const DEMO_CHANNELS: Channel[] = [
  {
    id: 1,
    name_ar: "أدوات النجارة",
    name_en: "Carpentry Tools",
    slug: "carpentry-tools",
    type: "trade",
    related_trade_id: 1,
    related_zone_id: null,
    source: "auto",
    is_active: true,
  },
  {
    id: 2,
    name_ar: "مواد لحام",
    name_en: "Welding Supplies",
    slug: "welding-supplies",
    type: "trade",
    related_trade_id: 7,
    related_zone_id: null,
    source: "auto",
    is_active: true,
  },
  {
    id: 3,
    name_ar: "إعمار دمشق",
    name_en: "Damascus Construction",
    slug: "damascus-construction",
    type: "zone",
    related_trade_id: null,
    related_zone_id: 1,
    source: "admin",
    is_active: true,
  },
  {
    id: 4,
    name_ar: "كهرباء وإضاءة",
    name_en: "Electrical Supplies",
    slug: "electrical",
    type: "trade",
    related_trade_id: 3,
    related_zone_id: null,
    source: "auto",
    is_active: true,
  },
];

export function getCraftsman(id: string): Craftsman | null {
  return DEMO_CRAFTSMEN.find((c) => c.id === id) ?? null;
}

export function getServicesFor(craftsmanId: string): Service[] {
  return DEMO_SERVICES.filter((s) => s.craftsman_id === craftsmanId);
}

export function getAssetsFor(craftsmanId: string): WorkshopAsset[] {
  return DEMO_WORKSHOP_ASSETS.filter((a) => a.craftsman_id === craftsmanId).map(
    (a) => ({
      ...a,
      asset_type:
        DEMO_ASSET_TYPES.find((at) => at.id === a.asset_type_id) ?? null,
    })
  );
}

export function getTrade(id: number | null): Trade | null {
  if (!id) return null;
  return DEMO_TRADES.find((t) => t.id === id) ?? null;
}

export function searchCraftsmen(filters: {
  q?: string;
  trade_id?: number | null;
  status?: "open" | "busy" | null;
  city_id?: number | null;
  asset_type_id?: number | null;
}): Craftsman[] {
  return DEMO_CRAFTSMEN.filter((c) => {
    if (c.approval_status !== "approved") return false;
    if (filters.trade_id && c.trade_id !== filters.trade_id) return false;
    if (filters.status && c.status !== filters.status) return false;
    if (filters.city_id && c.city_id !== filters.city_id) return false;
    if (filters.q) {
      const haystack =
        `${c.name} ${c.bio_ar ?? ""} ${c.bio_en ?? ""} ${c.location_name ?? ""}`.toLowerCase();
      if (!haystack.includes(filters.q.toLowerCase())) return false;
    }
    if (filters.asset_type_id) {
      const has = DEMO_WORKSHOP_ASSETS.some(
        (a) =>
          a.craftsman_id === c.id && a.asset_type_id === filters.asset_type_id
      );
      if (!has) return false;
    }
    return true;
  }).map((c) => ({
    ...c,
    trade: getTrade(c.trade_id),
    city: DEMO_CITIES.find((x) => x.id === c.city_id),
  }));
}
